2017-10-21 13:03:48,010 root INFO Test execution started: test_page.add_action_to_test
2017-10-21 13:03:48,011 root INFO Browser: chrome
2017-10-21 13:03:48,011 root INFO Environment: test
2017-10-21 13:03:48,012 root INFO Using data: 
    action: navigate
    url: http://localhost:8000

2017-10-21 13:03:48,019 root INFO Test does not have setup function
2017-10-21 13:03:49,039 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any"}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "chromeOptions": {"extensions": [], "args": []}}}
2017-10-21 13:03:53,156 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:53,157 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/window/current/maximize {"windowHandle": "current", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:53,399 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:53,400 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:53,458 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:53,959 root DEBUG Element not found yet, remaining time: 14.440331935882568
2017-10-21 13:03:53,960 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:53,969 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:54,469 root DEBUG Element not found yet, remaining time: 13.931082010269165
2017-10-21 13:03:54,469 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:54,479 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:54,979 root DEBUG Element not found yet, remaining time: 13.42107605934143
2017-10-21 13:03:54,980 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:54,990 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:55,491 root DEBUG Element not found yet, remaining time: 12.910221815109253
2017-10-21 13:03:55,491 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:55,501 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:56,001 root DEBUG Element not found yet, remaining time: 12.399986743927002
2017-10-21 13:03:56,002 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:56,013 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:56,513 root DEBUG Element not found yet, remaining time: 11.888567924499512
2017-10-21 13:03:56,514 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:56,523 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:57,024 root DEBUG Element not found yet, remaining time: 11.378480911254883
2017-10-21 13:03:57,024 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:57,034 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:57,534 root DEBUG Element not found yet, remaining time: 10.86793303489685
2017-10-21 13:03:57,535 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:57,544 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:58,045 root DEBUG Element not found yet, remaining time: 10.358150005340576
2017-10-21 13:03:58,045 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:58,054 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:58,554 root DEBUG Element not found yet, remaining time: 9.848987817764282
2017-10-21 13:03:58,555 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:58,564 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:59,064 root DEBUG Element not found yet, remaining time: 9.339391469955444
2017-10-21 13:03:59,065 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:59,074 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:03:59,574 root DEBUG Element not found yet, remaining time: 8.82986831665039
2017-10-21 13:03:59,574 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:03:59,584 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:00,085 root DEBUG Element not found yet, remaining time: 8.319014310836792
2017-10-21 13:04:00,086 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:00,095 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:00,595 root DEBUG Element not found yet, remaining time: 7.809701204299927
2017-10-21 13:04:00,595 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:00,604 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:01,104 root DEBUG Element not found yet, remaining time: 7.300657033920288
2017-10-21 13:04:01,105 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:01,114 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:01,614 root DEBUG Element not found yet, remaining time: 6.791376113891602
2017-10-21 13:04:01,614 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:01,623 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:02,123 root DEBUG Element not found yet, remaining time: 6.282411336898804
2017-10-21 13:04:02,124 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:02,132 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:02,632 root DEBUG Element not found yet, remaining time: 5.7736053466796875
2017-10-21 13:04:02,633 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:02,643 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:03,144 root DEBUG Element not found yet, remaining time: 5.2624053955078125
2017-10-21 13:04:03,145 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:03,154 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:03,654 root DEBUG Element not found yet, remaining time: 4.753612279891968
2017-10-21 13:04:03,654 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:03,663 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:04,163 root DEBUG Element not found yet, remaining time: 4.244694471359253
2017-10-21 13:04:04,163 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:04,172 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:04,673 root DEBUG Element not found yet, remaining time: 3.73553466796875
2017-10-21 13:04:04,673 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:04,681 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:05,182 root DEBUG Element not found yet, remaining time: 3.226482629776001
2017-10-21 13:04:05,182 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:05,192 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:05,693 root DEBUG Element not found yet, remaining time: 2.7159087657928467
2017-10-21 13:04:05,693 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:05,704 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:06,204 root DEBUG Element not found yet, remaining time: 2.205019474029541
2017-10-21 13:04:06,205 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:06,211 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:06,712 root DEBUG Element not found yet, remaining time: 1.6977543830871582
2017-10-21 13:04:06,712 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:06,719 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:07,220 root DEBUG Element not found yet, remaining time: 1.190098524093628
2017-10-21 13:04:07,220 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:07,226 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:07,727 root DEBUG Element not found yet, remaining time: 0.6829776763916016
2017-10-21 13:04:07,727 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:07,734 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:08,235 root DEBUG Element not found yet, remaining time: 0.1756727695465088
2017-10-21 13:04:08,235 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:08,243 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:08,743 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:08,751 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:09,251 root DEBUG Element not found yet, remaining time: 14.491644859313965
2017-10-21 13:04:09,252 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:09,257 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:09,758 root DEBUG Element not found yet, remaining time: 13.98544192314148
2017-10-21 13:04:09,758 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:09,764 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:10,265 root DEBUG Element not found yet, remaining time: 13.478855848312378
2017-10-21 13:04:10,265 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:10,271 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:10,771 root DEBUG Element not found yet, remaining time: 12.972142934799194
2017-10-21 13:04:10,772 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:10,779 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:11,279 root DEBUG Element not found yet, remaining time: 12.46458101272583
2017-10-21 13:04:11,280 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:11,287 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:11,787 root DEBUG Element not found yet, remaining time: 11.957166910171509
2017-10-21 13:04:11,787 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:11,795 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:12,295 root DEBUG Element not found yet, remaining time: 11.448945999145508
2017-10-21 13:04:12,296 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:12,302 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:12,803 root DEBUG Element not found yet, remaining time: 10.9412682056427
2017-10-21 13:04:12,804 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:12,811 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:13,311 root DEBUG Element not found yet, remaining time: 10.434054136276245
2017-10-21 13:04:13,311 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:13,318 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:13,818 root DEBUG Element not found yet, remaining time: 9.927484273910522
2017-10-21 13:04:13,818 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:13,825 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:14,325 root DEBUG Element not found yet, remaining time: 9.420729398727417
2017-10-21 13:04:14,325 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:14,331 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:14,832 root DEBUG Element not found yet, remaining time: 8.914250135421753
2017-10-21 13:04:14,832 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:14,843 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:15,344 root DEBUG Element not found yet, remaining time: 8.402583360671997
2017-10-21 13:04:15,344 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:15,353 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:15,854 root DEBUG Element not found yet, remaining time: 7.8930442333221436
2017-10-21 13:04:15,854 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:15,865 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:16,365 root DEBUG Element not found yet, remaining time: 7.381752252578735
2017-10-21 13:04:16,366 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:16,374 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:16,875 root DEBUG Element not found yet, remaining time: 6.872571229934692
2017-10-21 13:04:16,875 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:16,885 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:17,385 root DEBUG Element not found yet, remaining time: 6.3624444007873535
2017-10-21 13:04:17,386 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:17,395 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:17,895 root DEBUG Element not found yet, remaining time: 5.852713346481323
2017-10-21 13:04:17,896 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:17,907 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:18,407 root DEBUG Element not found yet, remaining time: 5.340987682342529
2017-10-21 13:04:18,408 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:18,417 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:18,918 root DEBUG Element not found yet, remaining time: 4.83100152015686
2017-10-21 13:04:18,918 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:18,928 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:19,429 root DEBUG Element not found yet, remaining time: 4.3200294971466064
2017-10-21 13:04:19,430 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:19,439 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:19,940 root DEBUG Element not found yet, remaining time: 3.8098983764648438
2017-10-21 13:04:19,940 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:19,950 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:20,451 root DEBUG Element not found yet, remaining time: 3.2994024753570557
2017-10-21 13:04:20,451 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:20,462 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:20,962 root DEBUG Element not found yet, remaining time: 2.787898302078247
2017-10-21 13:04:20,963 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:20,973 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:21,474 root DEBUG Element not found yet, remaining time: 2.276646375656128
2017-10-21 13:04:21,475 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:21,484 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:21,984 root DEBUG Element not found yet, remaining time: 1.766686201095581
2017-10-21 13:04:21,985 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:21,992 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:22,492 root DEBUG Element not found yet, remaining time: 1.2590172290802002
2017-10-21 13:04:22,493 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:22,499 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:23,000 root DEBUG Element not found yet, remaining time: 0.7519421577453613
2017-10-21 13:04:23,000 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:23,008 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:23,509 root DEBUG Element not found yet, remaining time: 0.2429952621459961
2017-10-21 13:04:23,509 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/element {"using": "id", "value": "testCasesTree", "sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:23,517 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:24,023 root INFO Take screenshot error
2017-10-21 13:04:24,023 selenium.webdriver.remote.remote_connection DEBUG GET http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073/screenshot {"sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:24,505 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:04:24,506 root ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 158, in create_access_test
    verify_test_exists(full_path)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 102, in verify_test_exists
    test_tree_ul = element(id='testCasesTree')
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 205, in element
    webelement = get_browser().find(**kwargs)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 114, in _find
    element_name, timeout)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  [Previous line repeated 25 more times]
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 48, in _find_webelement
    .format(element_name, selector_type, selector_value))
golem.core.exceptions.ElementNotFound: Element testCasesTree not found using selector id:'testCasesTree'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 114, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/test_page/add_action_to_test.py", line 10, in test
    project.create_access_test('testing_actions')
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 160, in create_access_test
    add_test(full_path)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 46, in add_test
    tests_tree_ul = element(id='testCasesTree')
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 205, in element
    webelement = get_browser().find(**kwargs)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 114, in _find
    element_name, timeout)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  [Previous line repeated 25 more times]
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 48, in _find_webelement
    .format(element_name, selector_type, selector_value))
golem.core.exceptions.ElementNotFound: Element testCasesTree not found using selector id:'testCasesTree'
2017-10-21 13:04:24,840 root INFO Test does not have a teardown function
2017-10-21 13:04:24,841 selenium.webdriver.remote.remote_connection DEBUG DELETE http://127.0.0.1:60667/session/193c89e1aa6919eeb75cfaddb2da4073 {"sessionId": "193c89e1aa6919eeb75cfaddb2da4073"}
2017-10-21 13:04:24,893 selenium.webdriver.remote.remote_connection DEBUG Finished Request
