2017-10-21 13:18:35,836 root INFO Test execution started: test_page.add_action_to_test
2017-10-21 13:18:35,837 root INFO Browser: chrome-headless
2017-10-21 13:18:35,838 root INFO Environment: test
2017-10-21 13:18:35,838 root INFO Using data: 
    action: click
    url: http://localhost:8000

2017-10-21 13:18:35,845 root INFO Test does not have setup function
2017-10-21 13:18:37,864 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "chrome", "platformName": "any"}}, "desiredCapabilities": {"browserName": "chrome", "version": "", "platform": "ANY", "chromeOptions": {"extensions": [], "args": ["headless", "--window-size=1600,1600"]}}}
2017-10-21 13:18:48,081 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:48,082 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/window/current/maximize {"windowHandle": "current", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:48,191 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:48,191 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:48,221 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:48,722 root DEBUG Element not found yet, remaining time: 14.46917986869812
2017-10-21 13:18:48,723 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:48,735 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:49,235 root DEBUG Element not found yet, remaining time: 13.956348896026611
2017-10-21 13:18:49,236 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:49,246 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:49,747 root DEBUG Element not found yet, remaining time: 13.445202827453613
2017-10-21 13:18:49,747 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:49,761 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:50,261 root DEBUG Element not found yet, remaining time: 12.931661605834961
2017-10-21 13:18:50,261 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:50,273 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:50,775 root DEBUG Element not found yet, remaining time: 12.41825556755066
2017-10-21 13:18:50,775 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:50,786 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:51,286 root DEBUG Element not found yet, remaining time: 11.90700650215149
2017-10-21 13:18:51,287 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:51,297 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:51,799 root DEBUG Element not found yet, remaining time: 11.394949674606323
2017-10-21 13:18:51,799 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:51,810 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:52,310 root DEBUG Element not found yet, remaining time: 10.883895635604858
2017-10-21 13:18:52,311 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:52,322 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:52,823 root DEBUG Element not found yet, remaining time: 10.371641635894775
2017-10-21 13:18:52,824 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:52,837 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:53,337 root DEBUG Element not found yet, remaining time: 9.857918500900269
2017-10-21 13:18:53,338 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:53,347 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:53,847 root DEBUG Element not found yet, remaining time: 9.348211526870728
2017-10-21 13:18:53,848 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:53,859 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:54,360 root DEBUG Element not found yet, remaining time: 8.836522340774536
2017-10-21 13:18:54,360 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:54,412 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:54,914 root DEBUG Element not found yet, remaining time: 8.283082246780396
2017-10-21 13:18:54,914 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:54,925 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:55,426 root DEBUG Element not found yet, remaining time: 7.77135705947876
2017-10-21 13:18:55,426 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:55,438 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:55,938 root DEBUG Element not found yet, remaining time: 7.259609937667847
2017-10-21 13:18:55,938 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:55,949 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:56,450 root DEBUG Element not found yet, remaining time: 6.748371124267578
2017-10-21 13:18:56,450 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:56,461 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:56,961 root DEBUG Element not found yet, remaining time: 6.2369513511657715
2017-10-21 13:18:56,962 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:56,972 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:57,473 root DEBUG Element not found yet, remaining time: 5.7261364459991455
2017-10-21 13:18:57,473 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:57,484 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:57,985 root DEBUG Element not found yet, remaining time: 5.214612722396851
2017-10-21 13:18:57,985 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:57,995 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:58,496 root DEBUG Element not found yet, remaining time: 4.7035887241363525
2017-10-21 13:18:58,496 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:58,508 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:59,008 root DEBUG Element not found yet, remaining time: 4.191694736480713
2017-10-21 13:18:59,009 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:59,020 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:18:59,521 root DEBUG Element not found yet, remaining time: 3.6795284748077393
2017-10-21 13:18:59,521 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:18:59,531 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:00,032 root DEBUG Element not found yet, remaining time: 3.1688005924224854
2017-10-21 13:19:00,032 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:00,042 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:00,543 root DEBUG Element not found yet, remaining time: 2.658315420150757
2017-10-21 13:19:00,543 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:00,553 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:01,053 root DEBUG Element not found yet, remaining time: 2.148068428039551
2017-10-21 13:19:01,054 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:01,064 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:01,565 root DEBUG Element not found yet, remaining time: 1.637223482131958
2017-10-21 13:19:01,565 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:01,575 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:02,075 root DEBUG Element not found yet, remaining time: 1.1272025108337402
2017-10-21 13:19:02,076 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:02,087 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:02,588 root DEBUG Element not found yet, remaining time: 0.6153097152709961
2017-10-21 13:19:02,588 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:02,597 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:03,098 root DEBUG Element not found yet, remaining time: 0.10576152801513672
2017-10-21 13:19:03,098 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:03,108 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:03,609 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:03,619 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:04,120 root DEBUG Element not found yet, remaining time: 14.488952875137329
2017-10-21 13:19:04,120 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:04,130 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:04,631 root DEBUG Element not found yet, remaining time: 13.978003025054932
2017-10-21 13:19:04,632 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:04,642 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:05,142 root DEBUG Element not found yet, remaining time: 13.46716022491455
2017-10-21 13:19:05,143 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:05,155 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:05,656 root DEBUG Element not found yet, remaining time: 12.954122066497803
2017-10-21 13:19:05,656 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:05,699 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:06,199 root DEBUG Element not found yet, remaining time: 12.410950183868408
2017-10-21 13:19:06,200 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:06,212 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:06,713 root DEBUG Element not found yet, remaining time: 11.898013353347778
2017-10-21 13:19:06,713 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:06,724 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:07,224 root DEBUG Element not found yet, remaining time: 11.387051582336426
2017-10-21 13:19:07,225 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:07,234 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:07,734 root DEBUG Element not found yet, remaining time: 10.877445459365845
2017-10-21 13:19:07,735 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:07,743 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:08,243 root DEBUG Element not found yet, remaining time: 10.368921518325806
2017-10-21 13:19:08,244 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:08,255 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:08,756 root DEBUG Element not found yet, remaining time: 9.856570482254028
2017-10-21 13:19:08,756 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:08,765 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:09,266 root DEBUG Element not found yet, remaining time: 9.346723556518555
2017-10-21 13:19:09,267 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:09,276 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:09,777 root DEBUG Element not found yet, remaining time: 8.83670449256897
2017-10-21 13:19:09,777 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:09,786 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:10,287 root DEBUG Element not found yet, remaining time: 8.326191425323486
2017-10-21 13:19:10,288 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:10,296 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:10,797 root DEBUG Element not found yet, remaining time: 7.817321538925171
2017-10-21 13:19:10,797 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:10,808 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:11,309 root DEBUG Element not found yet, remaining time: 7.304776668548584
2017-10-21 13:19:11,310 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:11,322 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:11,823 root DEBUG Element not found yet, remaining time: 6.791753530502319
2017-10-21 13:19:11,823 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:11,832 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:12,333 root DEBUG Element not found yet, remaining time: 6.282108783721924
2017-10-21 13:19:12,333 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:12,342 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:12,843 root DEBUG Element not found yet, remaining time: 5.772833585739136
2017-10-21 13:19:12,843 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:12,851 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:13,352 root DEBUG Element not found yet, remaining time: 5.263836860656738
2017-10-21 13:19:13,353 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:13,362 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:13,863 root DEBUG Element not found yet, remaining time: 4.753671884536743
2017-10-21 13:19:13,863 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:13,872 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:14,373 root DEBUG Element not found yet, remaining time: 4.243520975112915
2017-10-21 13:19:14,374 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:14,383 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:14,884 root DEBUG Element not found yet, remaining time: 3.7333507537841797
2017-10-21 13:19:14,884 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:14,891 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:15,392 root DEBUG Element not found yet, remaining time: 3.2253947257995605
2017-10-21 13:19:15,392 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:15,401 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:15,901 root DEBUG Element not found yet, remaining time: 2.7167646884918213
2017-10-21 13:19:15,901 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:15,909 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:16,410 root DEBUG Element not found yet, remaining time: 2.208322525024414
2017-10-21 13:19:16,410 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:16,418 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:16,919 root DEBUG Element not found yet, remaining time: 1.6995275020599365
2017-10-21 13:19:16,919 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:16,961 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:17,461 root DEBUG Element not found yet, remaining time: 1.157442569732666
2017-10-21 13:19:17,461 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:17,506 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:18,006 root DEBUG Element not found yet, remaining time: 0.6127567291259766
2017-10-21 13:19:18,006 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:18,015 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:18,516 root DEBUG Element not found yet, remaining time: 0.10331487655639648
2017-10-21 13:19:18,516 selenium.webdriver.remote.remote_connection DEBUG POST http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/element {"using": "id", "value": "testCasesTree", "sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:18,558 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:19,067 root INFO Take screenshot error
2017-10-21 13:19:19,069 selenium.webdriver.remote.remote_connection DEBUG GET http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9/screenshot {"sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:22,004 selenium.webdriver.remote.remote_connection DEBUG Finished Request
2017-10-21 13:19:22,005 root ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 158, in create_access_test
    verify_test_exists(full_path)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 102, in verify_test_exists
    test_tree_ul = element(id='testCasesTree')
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 205, in element
    webelement = get_browser().find(**kwargs)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 114, in _find
    element_name, timeout)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  [Previous line repeated 25 more times]
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 48, in _find_webelement
    .format(element_name, selector_type, selector_value))
golem.core.exceptions.ElementNotFound: Element testCasesTree not found using selector id:'testCasesTree'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 19, in _find_webelement
    webelement = root.find_element_by_id(selector_value)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 341, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"testCasesTree"}
  (Session info: headless chrome=61.0.3163.100)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 114, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/test_page/add_action_to_test.py", line 10, in test
    project.create_access_test('testing_actions')
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 160, in create_access_test
    add_test(full_path)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/pages/project.py", line 46, in add_test
    tests_tree_ul = element(id='testCasesTree')
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 205, in element
    webelement = get_browser().find(**kwargs)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 114, in _find
    element_name, timeout)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 45, in _find_webelement
    element_name, remaining_time)
  [Previous line repeated 25 more times]
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 48, in _find_webelement
    .format(element_name, selector_type, selector_value))
golem.core.exceptions.ElementNotFound: Element testCasesTree not found using selector id:'testCasesTree'
2017-10-21 13:19:22,016 root INFO Test does not have a teardown function
2017-10-21 13:19:22,017 selenium.webdriver.remote.remote_connection DEBUG DELETE http://127.0.0.1:51625/session/c69183652c2d2e758aa0549075ac8ed9 {"sessionId": "c69183652c2d2e758aa0549075ac8ed9"}
2017-10-21 13:19:22,069 selenium.webdriver.remote.remote_connection DEBUG Finished Request
