2017-10-12 21:09:10,862 root INFO Test execution started: product.add_product_to_cart_go_to_checkout
2017-10-12 21:09:10,863 root INFO Browser: chrome-remote
2017-10-12 21:09:10,865 root ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 114, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/store_demoqa/tests/product/add_product_to_cart_go_to_checkout.py", line 12, in test
    navigate('http://store.demoqa.com/')
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 145, in navigate
    driver = get_browser()
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 301, in get_browser
    desired_capabilities=DesiredCapabilities.CHROME)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 306, in execute
    response = self.command_executor.execute(driver_command, params)
AttributeError: 'NoneType' object has no attribute 'execute'
