{
    "test_case": "header.search_for_a_product",
    "result": "fail",
    "steps": [
        "error__3e1700d8"
    ],
    "description": "",
    "error": "Traceback (most recent call last):\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py\", line 93, in run_test\n    test_module.test(execution.data)\n  File \"/Users/lucianofeo/Desktop/golem/example/projects/store_demoqa/tests/header/search_for_a_product.py\", line 12, in test\n    navigate('http://store.demoqa.com/')\n  File \"/Users/lucianofeo/Desktop/golem/src/golem/actions.py\", line 140, in navigate\n    driver.get(url)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: timeout\n  (Session info: headless chrome=61.0.3163.100)\n  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.5 x86_64)\n\n",
    "short_error": "\n",
    "test_elapsed_time": 304.02,
    "test_timestamp": "2017.10.05.15.08.41.844",
    "browser": "chrome (headless)",
    "test_data": {}
}